# Generated by Django 4.2.25 on 2025-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО"
            ),
        ),
    ]
